# Generated by Django 6.1.1 on 2026-09-28 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('firebase_uid', models.CharField(max_length=200, unique=True)),
                ('role', models.CharField(default='cliente', max_length=20)),
                ('status', models.CharField(default='pendente', max_length=20)),
            ],
        ),
    ]
